### ISSUE TITLE
Unhandled panic

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#138]
While stress testing 500 tasks, I hit a panic

```
panic: runtime error: index out of range

goroutine 3758 [running]:
github.com/ohsu-comp-bio/funnel/util.NewDockerClient(0xc42000e468, 0x49f2366, 0x1b)
	/Users/buchanae/go/src/github.com/ohsu-comp-bio/funnel/util/docker.go:28 +0x20e
github.com/ohsu-comp-bio/funnel/worker.DockerCmd.Inspect(0xc42364b8d6, 0x6, 0xc42388d800, 0x2, 0x2, 0x4ee0d30, 0x0, 0x0, 0xc42364b924, 0xb, ...)
	/Users/buchanae/go/src/github.com/ohsu-comp-bio/funnel/worker/docker.go:92 +0xbb
github.com/ohsu-comp-bio/funnel/worker.(*stepRunner).inspectContainer(0xc4220a0300, 0x4e28740, 0xc4215f1b80)
	/Users/buchanae/go/src/github.com/ohsu-comp-bio/funnel/worker/step.go:94 +0x89
created by github.com/ohsu-comp-bio/funnel/worker.(*stepRunner).Run
	/Users/buchanae/go/src/github.com/ohsu-comp-bio/funnel/worker/step.go:50 +0x520
```

**Comment by buchanae** [comment]
I have two fixes for this already, by the way.

The panic happened because we're not checking if a slice is nil. Also, in #144 I add a `recover()` call to the task runner, so panics (hopefully) won't crash the worker.

Possibly we need a recover() for all individual goroutines though?
