### ISSUE TITLE
Server prints stack trace when it receives an unknown request method

### ISSUE THREAD

**Issue by adamstruck** [ohsu-comp-bio/funnel#179]
`curl -vvv -X POST http://localhost:8000/v1/tasks/foo` causes the server to panic. 

Logs:

```
server               HTTP handler error
error                Method Not Allowed
time                 2017-07-26T10:10:38-07:00
url                  /v1/tasks/foo

goroutine 98 [running]:
runtime/debug.Stack(0xc42014ee70, 0xc4204bb760, 0x400ee0f)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/ohsu-comp-bio/funnel/server.handleError(0x4e52b60, 0xc420502700, 0xc4202d0100, 0x49ff04f, 0x12, 0x195)
	/Users/strucka/go/src/github.com/ohsu-comp-bio/funnel/server/server.go:142 +0x1bd
github.com/ohsu-comp-bio/funnel/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime.(*ServeMux).ServeHTTP(0xc420370be0, 0x4e52b60, 0xc420502700, 0xc4202d0100)
	/Users/strucka/go/src/github.com/ohsu-comp-bio/funnel/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go:224 +0xc7d
github.com/ohsu-comp-bio/funnel/server.disableCache.func1(0x4e52b60, 0xc420502700, 0xc4202d0100)
	/Users/strucka/go/src/github.com/ohsu-comp-bio/funnel/server/server.go:151 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc42043cd40, 0x4e52b60, 0xc420502700, 0xc4202d0100)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc42044a270, 0x4e52b60, 0xc420502700, 0xc4202d0100)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4200c7ef0, 0x4e52b60, 0xc420502700, 0xc4202d0100)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42009e320, 0x4e53920, 0xc42041f380)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce
```

**Comment by adamstruck** [comment]
Comes from:  https://github.com/ohsu-comp-bio/funnel/blob/master/server/server.go#L142

Not sure what the benefit of printing this trace is. Logging an error seems sufficient.
