### ISSUE TITLE
cmd/task/list: unhandled panic

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#363]
```
./funnel task list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72e404]

goroutine 1 [running]:
net/http.(*Request).WithContext(0x0, 0x1c97b60, 0xc420010250, 0x1c97b60)
	/usr/local/go/src/net/http/request.go:332 +0x44
github.com/ohsu-comp-bio/funnel/client.(*Client).ListTasks(0xc4204782a0, 0x7f47d9c1a050, 0xc420010250, 0xc4201e5c50, 0xc420010250, 0xc4203d8d01, 0x6)
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/client/client.go:78 +0x221
github.com/ohsu-comp-bio/funnel/cmd/task.List(0xc42000a14e, 0x10, 0x13b9a22, 0x5, 0x0, 0x0, 0x0, 0x1c8d6a0, 0xc42000c018, 0xc4201e5d18, ...)
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/cmd/task/list.go:30 +0x1b8
github.com/ohsu-comp-bio/funnel/cmd/task.newCommandHooks.func3(0xc420476d80, 0x1d50a30, 0x0, 0x0, 0x0, 0x0)
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/cmd/task/task.go:64 +0xfc
github.com/ohsu-comp-bio/funnel/vendor/github.com/spf13/cobra.(*Command).execute(0xc420476d80, 0x1d50a30, 0x0, 0x0, 0xc420476d80, 0x1d50a30)
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/vendor/github.com/spf13/cobra/command.go:698 +0x47b
github.com/ohsu-comp-bio/funnel/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1d286a0, 0x1d29e00, 0x0, 0x0)
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/ohsu-comp-bio/funnel/vendor/github.com/spf13/cobra.(*Command).Execute(0x1d286a0, 0xc420000340, 0xc420000340)
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/buchanae/src/github.com/ohsu-comp-bio/funnel/main.go:10 +0x2d
```

**Comment by buchanae** [comment]
Seems to be related to this env. var: `export FUNNEL_SERVER=10.40.40.62:8000`

**Comment by buchanae** [comment]
More data:
```
funnel-server funnel
export FUNNEL_SERVER=10.40.40.62
funnel-server funnel
./funnel task list
Error: Get 10.40.40.62/v1/tasks?view=BASIC: unsupported protocol scheme ""
funnel-server funnel
export FUNNEL_SERVER=http://10.40.40.62:8000
funnel-server funnel
./funnel task list
{
  "tasks": [
    {
      "id": "b8esinnntf6l2ajpv0l0",
      "state": "QUEUED",
      "name": "Funnel run: sh -c \"echo hi\"",
      "resources": {

      },
      "executors": [
        {
          "image": "alpine",
          "command": [
            "sh",
            "-c",
            "echo hi"
          ],
          "workdir": "/opt/funnel",
          "stdout": "/opt/funnel/outputs/stdout-0",
          "stderr": "/opt/funnel/outputs/stderr-0"
        }
      ],
      "logs": [
        {

        }
      ],
      "creationTime": "2017-11-28T12:38:54.957213125-08:00"
    }
  ]
}
```

Looks like the CLI is very picky about the format of the funnel server address.
