### ISSUE TITLE
server: panic from cancel event

### ISSUE THREAD

**Issue by buchanae** [ohsu-comp-bio/funnel#445]
```
Jan 24 07:33:51 funnel-server funnel[8533]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 24 07:33:51 funnel-server funnel[8533]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1047c6a]
Jan 24 07:33:51 funnel-server funnel[8533]: goroutine 146569 [running]:
Jan 24 07:33:51 funnel-server funnel[8533]: github.com/ohsu-comp-bio/funnel/server.(*TaskService).CancelTask(0xc4201fb700, 0x7fd182a8c6d0, 0xc420648180, 0xc42065c330, 0xc4201fb700, 0x1551230, 0xc420550700
Jan 24 07:33:51 funnel-server funnel[8533]:         /Users/buchanae/src/github.com/ohsu-comp-bio/funnel/server/tes.go:66 +0x6a
Jan 24 07:33:51 funnel-server funnel[8533]: github.com/ohsu-comp-bio/funnel/proto/tes._TaskService_CancelTask_Handler.func1(0x7fd182a8c6d0, 0xc420648180, 0x13687a0, 0xc42065c330, 0x1, 0xc4203aa140, 0xc420
Jan 24 07:33:51 funnel-server funnel[8533]:         /Users/buchanae/src/github.com/ohsu-comp-bio/funnel/proto/tes/tes.pb.go:1292 +0x86
Jan 24 07:33:51 funnel-server funnel[8533]: github.com/ohsu-comp-bio/funnel/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x7fd182a8c6d0, 0xc420648180, 0x13687a0, 0xc42065c3
Jan 24 07:33:51 funnel-server funnel[8533]:         /Users/buchanae/src/github.com/ohsu-comp-bio/funnel/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:31 +0x107
Jan 24 07:33:51 funnel-server funnel[8533]: github.com/ohsu-comp-bio/funnel/server.newDebugInterceptor.func1(0x7fd182a8c6d0, 0xc420648180, 0x13687a0, 0xc42065c330, 0xc42024c5a0, 0xc4203aa0a0, 0x1eb02a0, 0
Jan 24 07:33:51 funnel-server funnel[8533]:         /Users/buchanae/src/github.com/ohsu-comp-bio/funnel/server/server.go:41 +0x19a
Jan 24 07:33:51 funnel-server funnel[8533]: github.com/ohsu-comp-bio/funnel/vendor/github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1(0x7fd182a8c6d0, 0xc420648180, 0x13687a0, 0xc42065c3
Jan 24 07:33:51 funnel-server funnel[8533]:         /Users/buchanae/src/github.com/ohsu-comp-bio/funnel/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x93
```

The line of the panic:
https://github.com/ohsu-comp-bio/funnel/blob/master/server/tes.go#L66

**Comment by buchanae** [comment]
```
/mnt/exa/funnel/funnel version
git commit: aa870f6
git branch: master
git upstream: git@github.com:ohsu-comp-bio/funnel.git
build date: Tue Jan 23 11:05:25 PST 2018
version: 0.5.0
```

**Comment by buchanae** [comment]
```
cat /mnt/exa/funnel/config.yml
Compute: manual
Server:
  HostName: redacted
  HTTPPort: 8081
  RPCPort: 9091

EventWriters: []

Database: mongodb
MongoDB:
  Addrs: ["redacted"]

Worker:
  WorkDir: /mnt/exa/funnel
  UpdateRate: 120000000000

LocalStorage:
  AllowedDirs:
    - /mnt/exa
```
